trigger:
- master
pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

variables:
- group: 'SamLearnsAzure KeyVault'
- name: vmImage #Note this weird name/value syntax if you need to reference a variable group in variables
  value: 'vs2017-win2016'

stages:
- stage: Build
  displayName: 'Build & Test stage'
  jobs:
  - template: azure-pipelines-build-template.yml
    parameters:
      buildConfiguration: 'Release'
      buildPlatform: 'Any CPU'
      vmImage: $(vmImage)


- stage: DeployDev
  displayName: 'Deploy Dev Stage'
  jobs:
  - template: azure-pipelines-deployment-template.yml
    parameters:
      applicationInsightsApiKey: '$(ApplicationInsights--APIKeyDev)'
      applicationInsightsApplicationId: '$(ApplicationInsights--ApplicationIdDev)'
      applicationInsightsInstrumentationKey: $(ApplicationInsights--InstrumentationKeyDev)
      applicationInsightsLocation: 'East US'
      appServiceContributerClientSecret: $(appServiceContributerClientSecret)
      cognitiveServicesSubscriptionKey: $(cognitiveServicesSubscriptionKey)
      environment: 'Dev'  
      environmentLowercase: 'dev'
      databaseLoginName: $(databaseLoginNameDev) 
      databaseLoginPassword: $(databaseLoginPasswordDev)
      databaseServerName: 'samsapp-dev-eu-sqlserver'
      letsEncryptUniqueRoleAssignmentGuid: '6e4cff57-e63a-403e-822c-e98e5ba02145'
      imagesStorageCDNURL: 'https://samsapp-dev-eu-cdnendpoint.azureedge.net/'
      imagesStorageURL: 'https://samsappdeveustorage.blob.core.windows.net/'
      redisCacheConnectionString: '$(AppSettings--RedisCacheConnectionStringDev)'
      resourceGroupName: 'SamLearnsAzureDev'
      resourceGroupLocation: 'East US'
      resourceGroupLocationShort: 'eu'
      roleAssignmentId: 'b24988ac-6180-42a0-ab88-20f7382dd24c'
      samsAppConnectionString: '$(ConnectionStrings--SamsAppConnectionStringDev)'
      serviceName: 'samsapp-dev-eu-service'
      serviceStagingUrl: 'https://samsapp-dev-eu-service-staging.azurewebsites.net/'
      serviceUrl: 'https://samsapp-dev-eu-service.azurewebsites.net/'
      storageAccountName: 'samsappdeveustorage'
      userPrincipalLogin: $(userPrincipalLogin)
      vmImage: $(vmImage)
      websiteName: 'samsapp-dev-eu-web'
      websiteDomainName: 'dev.samlearnsazure.com'
      websiteStagingUrl: 'https://samsapp-dev-eu-web-staging.azurewebsites.net/'
      websiteUrl: 'https://samsapp-dev-eu-web.azurewebsites.net/'


- stage: DeployQA
  displayName: 'Deploy QA Stage'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: azure-pipelines-deployment-template.yml
    parameters:
      applicationInsightsApiKey: '$(ApplicationInsights--APIKeyQA)'
      applicationInsightsApplicationId: '$(ApplicationInsights--ApplicationIdQA)'
      applicationInsightsInstrumentationKey: $(ApplicationInsights--InstrumentationKeyQA)
      applicationInsightsLocation: 'East US'
      appServiceContributerClientSecret: $(appServiceContributerClientSecret)
      cognitiveServicesSubscriptionKey: $(cognitiveServicesSubscriptionKey)
      environment: 'QA'  
      environmentLowercase: 'qa'
      databaseLoginName: $(databaseLoginNameQA) 
      databaseLoginPassword: $(databaseLoginPasswordQA)
      databaseServerName: 'samsapp-qa-eu-sqlserver'
      letsEncryptUniqueRoleAssignmentGuid: '6e4cff57-e63a-403e-822c-e98e5ba02146'
      imagesStorageCDNURL: 'https://samsapp-qa-eu-cdnendpoint.azureedge.net/'
      imagesStorageURL: 'https://samsappqaeustorage.blob.core.windows.net/'
      redisCacheConnectionString: '$(AppSettings--RedisCacheConnectionStringQA)'
      resourceGroupName: 'SamLearnsAzureQA'
      resourceGroupLocation: 'East US'
      resourceGroupLocationShort: 'eu'
      roleAssignmentId: 'b24988ac-6180-42a0-ab88-20f7382dd24c'
      samsAppConnectionString: '$(ConnectionStrings--SamsAppConnectionStringQA)'
      serviceName: 'samsapp-qa-eu-service'
      serviceStagingUrl: 'https://samsapp-qa-eu-service-staging.azurewebsites.net/'
      serviceUrl: 'https://samsapp-qa-eu-service.azurewebsites.net/'
      storageAccountName: 'samsappqaeustorage'
      userPrincipalLogin: $(userPrincipalLogin)
      vmImage: $(vmImage)
      websiteName: 'samsapp-qa-eu-web'
      websiteDomainName: 'qa.samlearnsazure.com'
      websiteStagingUrl: 'https://samsapp-qa-eu-web-staging.azurewebsites.net/'
      websiteUrl: 'https://samsapp-qa-eu-web.azurewebsites.net/'
      

- stage: DeployProd
  displayName: 'Deploy Prod Stage'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: azure-pipelines-deployment-template.yml
    parameters:
      applicationInsightsApiKey: '$(ApplicationInsights--APIKeyProd)'
      applicationInsightsApplicationId: '$(ApplicationInsights--ApplicationIdProd)'
      applicationInsightsInstrumentationKey: $(ApplicationInsights--InstrumentationKeyProd)
      applicationInsightsLocation: 'East US'
      appServiceContributerClientSecret: $(appServiceContributerClientSecret)
      cognitiveServicesSubscriptionKey: $(cognitiveServicesSubscriptionKey)
      environment: 'Prod'  
      environmentLowercase: 'prod'
      databaseLoginName: $(databaseLoginNameProd) 
      databaseLoginPassword: $(databaseLoginPasswordProd)
      databaseServerName: 'samsapp-prod-eu-sqlserver'
      letsEncryptUniqueRoleAssignmentGuid: '6e4cff57-e63a-403e-822c-e98e5ba02147'
      imagesStorageCDNURL: 'https://samsapp-prod-eu-cdnendpoint.azureedge.net/'
      imagesStorageURL: 'https://samsappprodeustorage.blob.core.windows.net/'
      redisCacheConnectionString: '$(AppSettings--RedisCacheConnectionStringProd)'
      resourceGroupName: 'SamLearnsAzureProd'
      resourceGroupLocation: 'East US'
      resourceGroupLocationShort: 'eu'
      roleAssignmentId: 'b24988ac-6180-42a0-ab88-20f7382dd24c'
      samsAppConnectionString: '$(ConnectionStrings--SamsAppConnectionStringProd)'
      serviceName: 'samsapp-prod-eu-service'
      serviceStagingUrl: 'https://samsapp-prod-eu-service-staging.azurewebsites.net/'
      serviceUrl: 'https://samsapp-prod-eu-service.azurewebsites.net/'
      storageAccountName: 'samsappprodeustorage'
      userPrincipalLogin: $(userPrincipalLogin)
      vmImage: $(vmImage)
      websiteName: 'samsapp-prod-eu-web'
      websiteDomainName: 'samlearnsazure.com'
      websiteStagingUrl: 'https://samsapp-prod-eu-web-staging.azurewebsites.net/'
      websiteUrl: 'https://samsapp-prod-eu-web.azurewebsites.net/'
      