# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  BuildConfiguration: 'Release'
  BuildPlatform : 'Any CPU'

steps:

#Dotnet Core build items
- task: DotNetCoreCLI@2
  displayName: 'Restore dotnet core projects'
  inputs:
    command: restore
    projects: |
     **/SamLearnsAzure/SamLearnsAzure.Service/SamLearnsAzure.Service.csproj

- task: DotNetCoreCLI@2
  displayName: 'Build dotnet core projects'
  inputs:
    command: build
    projects: |
     **/SamLearnsAzure/SamLearnsAzure.Service/SamLearnsAzure.Service.csproj
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish dotnet core projects'
  inputs:
    command: publish
    publishWebProjects: false
    projects: |
     **/SamLearnsAzure/SamLearnsAzure.Service/SamLearnsAzure.Service.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: true
