parameters: # defaults for any parameters that aren't specified
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  vmImage: 'windows-latest'

jobs:
  - job: Build
    displayName: 'Build job'
    pool:
      vmImage: ${{parameters.vmImage}}
    variables:
      buildNumber: '1.0.0.0'
    steps:

    # DotNet Framework build items
    - task: NuGetToolInstaller@0
      displayName: 'Use NuGet 4.4.1'
      inputs:
        versionSpec: 4.4.1

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        projects: |
         SamLearnsAzure/SamLearnsAzure.Database/SamLearnsAzure.Database.sqlproj
        vstsFeed: '030a758a-428f-4445-bce8-2c19ad9a56b3'

    - task: VSBuild@1
      displayName: 'Build database project'
      inputs:
        platform: '${{parameters.buildPlatform}}'
        configuration: '${{parameters.buildConfiguration}}'
        solution: SamLearnsAzure/SamLearnsAzure.Database/SamLearnsAzure.Database.sqlproj

    - task: CopyFiles@2
      displayName: 'Copy database files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)\SamLearnsAzure\SamLearnsAzure.Database\bin\Output'
        Contents: '*' # * = Copy all files in the current directory
        TargetFolder: '$(build.artifactstagingdirectory)\Database'

    # Publish the artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

    # Run security tasks
    - task: ms-codeanalysis.vss-microsoft-security-code-analysis.build-task-credscan.CredScan@2
      displayName: 'Run CredScan'
    #- task: ms-codeanalysis.vss-microsoft-security-code-analysis.build-task-postanalysis.PostAnalysis@1
    #  displayName: 'Post Analysis'
    #  inputs:
    #    CredScan: true