parameters: # defaults for any parameters that aren't specified
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  vmImage: 'windows-latest'
  clientSecret: '***secret'
  redisCacheConnectionString: '***secret'
  storageAccountKey: '***secret'

jobs:


  - job: BuildDotNet5
    displayName: 'Build .NET 5 apps'
    pool:
      vmImage: ${{parameters.vmImage}}
    variables:
      buildNumber: '1.0.0.0'
    steps:
    - task: dutchworkz.DisplayAllVariables.DisplayAllVariables.DutchWorkzToolsAllVariables@1
      displayName: 'Show all build variables in build output.'
    - task: PowerShell@2
      displayName: 'Generate build version number'
      inputs:
        targetType: FilePath
        filePath: SamLearnsAzure/BuildVersion.ps1
        arguments: -ProjectFile "SamLearnsAzure/SamLearnsAzure.Web/SamLearnsAzure.Web.csproj"
    - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
      displayName: 'Prepare analysis on SonarCloud'
      inputs:
        SonarCloud: 'SonarQube connection'
        organization: samsmithnz
        projectKey: SamLearnsAzure
    - task: DotNetCoreCLI@2
      displayName: 'Restore dotnet 5 projects'
      inputs:
        command: restore
        projects: |
         SamLearnsAzure/SamLearnsAzure.Service/SamLearnsAzure.Service.csproj
         SamLearnsAzure/SamLearnsAzure.Web/SamLearnsAzure.Web.csproj
        vstsFeed: '030a758a-428f-4445-bce8-2c19ad9a56b3'
    - task: DotNetCoreCLI@2
      displayName: 'Publish dotnet 5 projects'
      inputs:
        command: publish
        publishWebProjects: false
        projects: |
         SamLearnsAzure/SamLearnsAzure.Service/SamLearnsAzure.Service.csproj
         SamLearnsAzure/SamLearnsAzure.Web/SamLearnsAzure.Web.csproj
        arguments: '--configuration ${{parameters.buildConfiguration}} --output $(build.artifactstagingdirectory) -p:Version=$(buildNumber) --self-contained true --runtime win-x86'
        zipAfterPublish: true
    - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
      displayName: 'Run Code Analysis on SonarCloud'
      enabled: true
    - task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
      displayName: 'Publish Quality Gate Result on SonarCloud'
      enabled: true
    # Run security tasks
    - task: ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-credscan.CredScan@2
      displayName: 'Run CredScan'
      inputs:
        suppressionsFile: SamLearnsAzure/CredScan/CredScanSuppressions.json
      enabled: false
    - task: WhiteSource Bolt@19
      enabled: true
    #Confirm that security tasks passed successfully before finalizing the build
    - task: ms-codeanalysis.vss-microsoft-security-code-analysis-devops.build-task-postanalysis.PostAnalysis@1
      displayName: 'Post Analysis'
      inputs:
        CredScan: true
      enabled: false
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'


  - job: BuildDotNet6
    displayName: 'Build .NET 6 apps'
    pool:
      vmImage: ${{parameters.vmImage}}
    variables:
      buildNumber: '1.0.0.0'
    steps:
    - task: dutchworkz.DisplayAllVariables.DisplayAllVariables.DutchWorkzToolsAllVariables@1
      displayName: 'Show all build variables in build output.'
    - task: PowerShell@2
      displayName: 'Generate build version number'
      inputs:
        targetType: FilePath
        filePath: SamLearnsAzure/BuildVersion.ps1
        arguments: -ProjectFile "SamLearnsAzure/SamLearnsAzure.Web2/SamLearnsAzure.Web2.csproj"
    - task: UseDotNet@2
      displayName: 'Install .NET 6 SDK'
      inputs:
        packageType: 'sdk'
        version: '6.0.100-preview.1.21103.13'
    - task: DotNetCoreCLI@2
      displayName: 'Restore dotnet 6 projects'
      inputs:
        command: restore
        projects: |
         SamLearnsAzure/SamLearnsAzure.Service2/SamLearnsAzure.Service2.csproj
         SamLearnsAzure/SamLearnsAzure.Web2/SamLearnsAzure.Web2.csproj
        vstsFeed: '030a758a-428f-4445-bce8-2c19ad9a56b3'
    - task: DotNetCoreCLI@2
      displayName: 'Publish dotnet 6 projects'
      inputs:
        command: publish
        publishWebProjects: false
        projects: |
         SamLearnsAzure/SamLearnsAzure.Service2/SamLearnsAzure.Service2.csproj
         SamLearnsAzure/SamLearnsAzure.Web2/SamLearnsAzure.Web2.csproj
        arguments: '--configuration ${{parameters.buildConfiguration}} --output $(build.artifactstagingdirectory) -p:Version=$(buildNumber) --self-contained true --runtime win-x86'
        zipAfterPublish: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'


  - job: BuildUnitTest
    displayName: 'Run unit tests'
    pool:
      vmImage: ${{parameters.vmImage}}
    variables:
      buildNumber: '1.0.0.0'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore dotnet 5 projects'
      inputs:
        command: restore
        projects: |
         SamLearnsAzure/SamLearnsAzure.Tests/SamLearnsAzure.Tests.csproj
        vstsFeed: '030a758a-428f-4445-bce8-2c19ad9a56b3'
    - powershell: |  
        $pathToJson = "SamLearnsAzure/SamLearnsAzure.Tests/appsettings.json"
        $a = Get-Content $pathToJson | ConvertFrom-Json
        $a.AppSettings.ClientSecret = "${{parameters.clientSecret}}"
        $a.AppSettings.RedisCacheConnectionString = "${{parameters.redisCacheConnectionString}}"
        $a | ConvertTo-Json | set-content $pathToJson   
    - task: DotNetCoreCLI@2
      displayName: 'Test dotnet 5 projects'
      inputs:
        command: test
        projects: |
         SamLearnsAzure/SamLearnsAzure.Tests/SamLearnsAzure.Tests.csproj
        arguments: '--configuration ${{parameters.buildConfiguration}} --filter TestCategory=UnitTest --logger trx --collect "Code coverage" --settings:$(Build.SourcesDirectory)\SamLearnsAzure\SamLearnsAzure.Tests\CodeCoverage.runsettings'
        vstsFeed: '030a758a-428f-4445-bce8-2c19ad9a56b3' 
      enabled: true

  - job: BuildServiceAIntegrationTest
    displayName: 'Service int tests part A'
    pool:
      vmImage: ${{parameters.vmImage}}
    variables:
      buildNumber: '1.0.0.0'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore dotnet 5 projects'
      inputs:
        command: restore
        projects: |
         SamLearnsAzure/SamLearnsAzure.Tests/SamLearnsAzure.Tests.csproj
        vstsFeed: '030a758a-428f-4445-bce8-2c19ad9a56b3'
    - powershell: |  
        $pathToJson = "SamLearnsAzure/SamLearnsAzure.Tests/appsettings.json"
        $a = Get-Content $pathToJson | ConvertFrom-Json
        $a.AppSettings.ClientSecret = "${{parameters.clientSecret}}"
        $a.AppSettings.RedisCacheConnectionString = "${{parameters.redisCacheConnectionString}}"
        $a | ConvertTo-Json | set-content $pathToJson   
    - task: DotNetCoreCLI@2
      displayName: 'Test dotnet 5 projects'
      inputs:
        command: test
        projects: |
         SamLearnsAzure/SamLearnsAzure.Tests/SamLearnsAzure.Tests.csproj
        arguments: '--configuration ${{parameters.buildConfiguration}} --filter TestCategory=ServiceIntegrationTestA --logger trx --collect "Code coverage" --settings:$(Build.SourcesDirectory)\SamLearnsAzure\SamLearnsAzure.Tests\CodeCoverage.runsettings'
        vstsFeed: '030a758a-428f-4445-bce8-2c19ad9a56b3' 
      enabled: true

  - job: BuildServiceBIntegrationTest
    displayName: 'Service int tests part B'
    pool:
      vmImage: ${{parameters.vmImage}}
    variables:
      buildNumber: '1.0.0.0'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore dotnet 5 projects'
      inputs:
        command: restore
        projects: |
         SamLearnsAzure/SamLearnsAzure.Tests/SamLearnsAzure.Tests.csproj
        vstsFeed: '030a758a-428f-4445-bce8-2c19ad9a56b3'
    - powershell: |  
        $pathToJson = "SamLearnsAzure/SamLearnsAzure.Tests/appsettings.json"
        $a = Get-Content $pathToJson | ConvertFrom-Json
        $a.AppSettings.ClientSecret = "${{parameters.clientSecret}}"
        $a.AppSettings.RedisCacheConnectionString = "${{parameters.redisCacheConnectionString}}"
        $a | ConvertTo-Json | set-content $pathToJson   
    - task: DotNetCoreCLI@2
      displayName: 'Test dotnet 5 projects'
      inputs:
        command: test
        projects: |
         SamLearnsAzure/SamLearnsAzure.Tests/SamLearnsAzure.Tests.csproj
        arguments: '--configuration ${{parameters.buildConfiguration}} --filter TestCategory=ServiceIntegrationTestB --logger trx --collect "Code coverage" --settings:$(Build.SourcesDirectory)\SamLearnsAzure\SamLearnsAzure.Tests\CodeCoverage.runsettings'
        vstsFeed: '030a758a-428f-4445-bce8-2c19ad9a56b3' 
      enabled: true

  - job: BuildWebIntegrationTest
    displayName: 'Website integration tests'
    pool:
      vmImage: ${{parameters.vmImage}}
    variables:
      buildNumber: '1.0.0.0'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore dotnet 5 projects'
      inputs:
        command: restore
        projects: |
         SamLearnsAzure/SamLearnsAzure.Tests/SamLearnsAzure.Tests.csproj
        vstsFeed: '030a758a-428f-4445-bce8-2c19ad9a56b3'
    - powershell: |  
        $pathToJson = "SamLearnsAzure/SamLearnsAzure.Tests/appsettings.json"
        $a = Get-Content $pathToJson | ConvertFrom-Json
        $a.AppSettings.ClientSecret = "${{parameters.clientSecret}}"
        $a.AppSettings.RedisCacheConnectionString = "${{parameters.redisCacheConnectionString}}"
        $a | ConvertTo-Json | set-content $pathToJson   
    - task: DotNetCoreCLI@2
      displayName: 'Test dotnet 5 projects'
      inputs:
        command: test
        projects: |
         SamLearnsAzure/SamLearnsAzure.Tests/SamLearnsAzure.Tests.csproj
        arguments: '--configuration ${{parameters.buildConfiguration}} --filter TestCategory=WebIntegrationTest --logger trx --collect "Code coverage" --settings:$(Build.SourcesDirectory)\SamLearnsAzure\SamLearnsAzure.Tests\CodeCoverage.runsettings'
        vstsFeed: '030a758a-428f-4445-bce8-2c19ad9a56b3' 
      enabled: false


  - job: BuildFunctional
    displayName: 'Run functional tests'
    pool:
      vmImage: ${{parameters.vmImage}}
    variables:
      buildNumber: '1.0.0.0'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Restore dotnet 5 projects'
      inputs:
        command: restore
        projects: |
         SamLearnsAzure/SamLearnsAzure.FunctionalTests/SamLearnsAzure.FunctionalTests.csproj
        vstsFeed: '030a758a-428f-4445-bce8-2c19ad9a56b3'
    - task: DotNetCoreCLI@2
      displayName: 'Publish dotnet 5 functional tests project'
      inputs:
        command: publish
        publishWebProjects: false
        projects: |
         SamLearnsAzure/SamLearnsAzure.FunctionalTests/SamLearnsAzure.FunctionalTests.csproj
        arguments: '--configuration ${{parameters.buildConfiguration}} --output $(build.artifactstagingdirectory)/FunctionalTests'
        zipAfterPublish: false
    - task: CopyFiles@2
      displayName: 'Copy Selenium Files to: $(build.artifactstagingdirectory)/FunctionalTests/SamLearnsAzure.FunctionalTests'
      inputs:
        SourceFolder: 'SamLearnsAzure/SamLearnsAzure.FunctionalTests/bin/${{parameters.buildConfiguration}}/net5.0'
        Contents: '*chromedriver.exe*'
        TargetFolder: '$(build.artifactstagingdirectory)/FunctionalTests/SamLearnsAzure.FunctionalTests'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'


  - job: BuildARMTemplates
    displayName: 'Build ARM templates'
    pool:
      vmImage: ${{parameters.vmImage}}
    steps:
    - task: CopyFiles@2
      displayName: 'Copy environment ARM template files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)\SamLearnsAzure\SamLearnsAzure.Environment.ARMTemplate'
        Contents: '**\*' # **\* = Copy all files and all files in sub directories
        TargetFolder: '$(build.artifactstagingdirectory)\EnvironmentARMTemplate'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'


  - job: BuildDotNetFramework
    displayName: 'Build .NET Framework'
    pool:
      vmImage: ${{parameters.vmImage}}
    steps:
    - task: VSBuild@1
      displayName: 'Build database project'
      inputs:
        platform: '${{parameters.buildPlatform}}'
        configuration: '${{parameters.buildConfiguration}}'
        solution: SamLearnsAzure/SamLearnsAzure.Database/SamLearnsAzure.Database.sqlproj
    - task: CopyFiles@2
      displayName: 'Copy database files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)\SamLearnsAzure\SamLearnsAzure.Database\bin\Output'
        Contents: '*' # * = Copy all files in the current directory
        TargetFolder: '$(build.artifactstagingdirectory)\Database'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

  - job: CleanUpKeyVault
    displayName: 'Clean up key vault'
    pool:
      vmImage: ${{parameters.vmImage}}
    dependsOn: 
    - BuildARMTemplates
    steps:
    - task: DownloadBuildArtifacts@0
      displayName: 'Download the build artifacts'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(build.artifactstagingdirectory)'
    - task: AzureCLI@2
      displayName: 'Deploy infrastructure with ARM templates'
      inputs:
        azureSubscription: 'SamLearnsAzure connection to Azure Portal'
        scriptType: ps
        scriptPath: $(build.artifactstagingdirectory)\drop\EnvironmentARMTemplate\PowerShell\KeyVaultCleanup.ps1
        arguments: -storageAccountKey ${{parameters.storageAccountKey}}
      enabled: true