
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:SamLearnsAzure.Service.Controllers.SetImagesController.GetSetImage(System.String,System.Boolean,System.Boolean)~System.Threading.Tasks.Task{SamLearnsAzure.Models.SetImages}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:SamLearnsAzure.Service.DataAccess.SetImagesRepository.GetSetImage(SamLearnsAzure.Service.DataAccess.IRedisService,System.Boolean,System.String)~System.Threading.Tasks.Task{SamLearnsAzure.Models.SetImages}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~M:SamLearnsAzure.Service.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IHostingEnvironment)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:SamLearnsAzure.Service.Controllers.SetImagesController.SaveImageIntoBlob(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:SamLearnsAzure.Service.Controllers.SetImagesController.GetSetImage(System.String,System.Boolean,System.Boolean,System.Int32)~System.Threading.Tasks.Task{SamLearnsAzure.Models.SetImages}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:SamLearnsAzure.Service.Controllers.SetImagesController.GetSetImages(System.String,System.Boolean,System.Boolean,System.Int32)~System.Threading.Tasks.Task{System.Collections.Generic.List{SamLearnsAzure.Models.SetImages}}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:SamLearnsAzure.Service.Controllers.SetImagesController.ImageAnalysisSearch(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{System.Boolean}")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "<Pending>", Scope = "member", Target = "~M:SamLearnsAzure.Service.AI.ImageAnalysis.PerformImageAnalysisSearch(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Vulnerability", "S1104:Fields should not have public accessibility", Justification = "<Pending>", Scope = "member", Target = "~F:SamLearnsAzure.Service.AI.BingImageSearch.SearchResult.jsonResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Vulnerability", "S1104:Fields should not have public accessibility", Justification = "<Pending>", Scope = "member", Target = "~F:SamLearnsAzure.Service.AI.BingImageSearch.SearchResult.relevantHeaders")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:SamLearnsAzure.Service.Controllers.SetImagesController.GetSetImages(System.String,System.Boolean,System.Boolean,System.Int32,System.Int32)~System.Threading.Tasks.Task{System.Collections.Generic.List{SamLearnsAzure.Models.SetImages}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:SamLearnsAzure.Service.Controllers.SetImagesController.GetSetImage(System.String,System.Boolean,System.Boolean,System.Int32,System.Int32)~System.Threading.Tasks.Task{SamLearnsAzure.Models.SetImages}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Minor Code Smell", "S1125:Boolean literals should not be redundant", Justification = "<Pending>", Scope = "member", Target = "~M:SamLearnsAzure.Service.AI.BingImageSearch.PerformBingImageSearch(System.String,System.String,System.String,System.String,System.Int32,System.Int32,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{SamLearnsAzure.Models.SetImages}}")]

